### ISSUE TITLE
Some documentation is added out of order

### ISSUE THREAD

**Issue by aaronhowser1** [aaronhowser1/Document-Your-Mod-Mod#6]
`rope__dispenser.json` loads before `rope.json`, which means 
![image](https://user-images.githubusercontent.com/15698722/62405785-7aeb2300-b567-11e9-8068-69e0b4ec33d6.png)
this is the first page of the documentation, instead of 
![image](https://user-images.githubusercontent.com/15698722/62405788-83435e00-b567-11e9-8fa4-259074c02f0b.png)

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/63052067-16539080-bea4-11e9-9b1f-e6ff1d97644c.png)
because I keep forgetting to do this, putting a reminder here

**Comment by aaronhowser1** [comment]
This time it loaded it correctly. Weird.

[debug.log](https://github.com/aaronhowser1/Document-Your-Mod-Mod/files/3507322/debug.log)
[latest.log](https://github.com/aaronhowser1/Document-Your-Mod-Mod/files/3507323/latest.log)

@TheSilkMiner

**Comment by TheSilkMiner** [comment]
The log doesn't give any clue here, it seems stuff is getting loaded correctly in alphabetical order. It is probably a one-off error, but relying on something that is as ephemeral as that is probably a Very-Bad-Idea™.

**Proposed fix:**
Add a `dependencies` optional section in the JSON file that acts similar to Forge's `Mod#dependencies` string.

<details><summary><strong>Schema:</strong></summary>

```json
"requirements": [
  {
    "order": "before" | "after",
    "required": true | false (optional, assumed false),
    "registry_name": "modid:registry_name"
  }, (multiple supported)
]
```

</details>

**Questions**
- Should cross-mod requirements be handled or ignored? (e.g. `tconstruct:ladder` that depends on `quark:stairs`)
- In case a cyclic dependency is present, should it be undefined behavior (no particular loading order) or should it outright crash?
- In case of multiple conflicting requirements (e.g. a before and after that match the same registry name for the same entry), should the loading crash or the entry be skipped with a warning?
- Should not satisfied requirements cause a crash?

**Comment by TheSilkMiner** [comment]
![Discord Integration](https://user-images.githubusercontent.com/11136677/63650112-5d187480-c747-11e9-8d81-510375ec2568.png)
<details><summary></summary>

- Handled
- Crash
- Crash
- No

</details>
